// AUTO-GENERATED by scripts/generate-image-manifest.mjs
// Convert/rename images freely, then run: node scripts/generate-image-manifest.mjs
export const IMAGE_ASSETS = {
  "home/agency": "/images/home/agency.jpg",
  "home/audience": "/images/home/audience.jpg",
  "home/insights": "/images/home/insights.png",
  "home/why-phantom": "/images/home/why-phantom.png",
  "services/ai-search": "/images/services/ai-search.jpg",
  "services/animation": "/images/services/animation.jpg",
  "services/branding": "/images/services/branding.png",
  "services/creative": "/images/services/creative.png",
  "services/paid-media": "/images/services/paid-media.png",
  "services/pr-marketing": "/images/services/pr-marketing.jpg",
  "services/print-services": "/images/services/print-services.jpg",
  "services/search": "/images/services/search.jpg",
  "services/social-media": "/images/services/social-media.png",
  "services/web-design": "/images/services/web-design.png",
  "services/web-development": "/images/services/web-development.png"
} as const;
export type ImageAssetKey = keyof typeof IMAGE_ASSETS;
export function imageAsset(key: ImageAssetKey | string){ return (IMAGE_ASSETS as Record<string,string>)[key] || ''; }
