import type {Metadata} from "next";
import PhantomServicePage,{type ServiceData} from "@/components/services/PhantomServicePage";
const d:ServiceData={"title": "Google Ads", "eyebrow": "GOOGLE ADS", "hero": "Command the Clicks. Conquer the SERP.", "introTitle": "Ad Alchemy That Works", "intro": "Attention is currency. Phantom builds Google Ads around intent, message, landing-page alignment and relentless optimization instead of throwing budget into keyword chaos.", "services": ["Search Ads: The High-Intent Hex", "Display Ads: Banner Sorcery", "Shopping Ads", "YouTube Ads", "Performance Max", "App Campaigns", "Demand Gen", "Remarketing & Local Intent"],
"serviceCards":[
{"title":"Search Ads","description":"Capture high-intent demand from people actively searching for relevant products, services and solutions.","href":"/google-ads/search-ads"},
{"title":"Display Ads","description":"Build awareness, remarketing and audience reach through visual advertising across Google's display inventory.","href":"/google-ads/display-ads"},
{"title":"Shopping Ads","description":"Put product information in front of commercial searches using feed-led advertising built around purchase intent.","href":"/google-ads/shopping-ads"},
{"title":"Video Ads","description":"Use YouTube and Google's video inventory to combine audience targeting, creative storytelling and measurable action.","href":"/google-ads/video-ads"},
{"title":"Performance Max","description":"Coordinate eligible Google inventory around stronger assets, audience signals, conversion data and business goals.","href":"/google-ads/performance-max"},
{"title":"Demand Gen","description":"Create demand through visual campaigns designed for discovery, consideration and audience-led acquisition.","href":"/google-ads/demand-gen"},
{"title":"App Advertising","description":"Drive app installs and valuable in-app actions with campaigns built around measurement and user quality.","href":"/google-ads/app-advertising"},
{"title":"Local Search","description":"Capture location-driven demand from people searching for relevant businesses, products and services nearby.","href":"/google-ads/local-search"}
], "failures": ["Irrelevant keywords draining budget", "Weak copy and creatives", "Sending paid traffic to weak landing pages"], "process": ["Discovery & Keyword Necromancy", "Campaign Casting", "Conversion Tracking", "Landing Page Possession", "Optimization Offerings", "A/B Hex Testing"], "arsenal": ["Google Ads", "Keyword Planner", "GA4", "Google Tag Manager", "Merchant Center", "Looker Studio"], "faqs": [["How quickly can Google Ads generate traffic?", "Campaigns can generate traffic after launch, but efficient performance usually needs data, testing and ongoing optimization."], ["Do you manage conversion tracking?", "Tracking validation is a core part of responsible paid media management."], ["Do you guarantee ROAS?", "No. Outcomes depend on market, offer, margins, website, competition and budget; optimization focuses on measurable business goals."], ["How does Phantom approach Google Ads?", "We start with the audience, market, objective and current digital setup, then build the Google Ads plan around those realities rather than a copied template."], ["How soon can Google Ads be launched?", "Timing depends on access, tracking, creative or technical requirements, and the scope agreed during discovery."], ["How do you measure Google Ads performance?", "We define relevant success signals before execution and review them alongside the quality of traffic, leads, engagement or visibility generated."]], "valueTitle": "Google Ads: Turn Paid Attention Into Measurable Action", "valueIntro": "Google Ads is not just about being present. The businesses that win use it to create stronger visibility, a clearer customer journey and a repeatable path from attention to meaningful action.", "valueBullets": ["Reach high-value audiences — put budget behind people and moments with real commercial potential.", "Turn clicks and views into leads or customers — because paid traffic without a next step only burns budget.", "Test, learn and scale deliberately — use campaign signals to improve creative, targeting, landing journeys and spend."], "choiceTitle": "The Choice is Yours… Watch the Clicks Pass or Command Search Demand", "choiceCopy": "People are searching with intent right now. Meet that demand with sharper targeting, stronger journeys and measurement that matters.", "choiceButton": "COMMAND THE CLICKS!"};
export const metadata:Metadata={title:`${d.title} | Phantom Marketing`,description:d.intro,alternates:{canonical:"/google-ads"}};
export default function Page(){return <PhantomServicePage d={d}/>}
